spring:
  application:
    name: challange-cryptography
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  datasource:
    url: jdbc:h2:mem:userdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      settings:
        trace: true
      path: /h2-console
